databases:
  - name: TravelSite
    databaseName: TravelSite
    user: TravelSite

services:
  - type: web
    name: TravelSite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn TravelSite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TravelSite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4