# Generated by Django 4.1.3 on 2022-12-20 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_delete_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ("-id",)},),
        migrations.RemoveField(model_name="comment", name="text",),
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_comments",
                to="stories.story",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
