# Generated by Django 4.1.3 on 2022-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="story", old_name="body", new_name="story",),
        migrations.AddField(
            model_name="story",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
