# Generated by Django 4.1.3 on 2022-11-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_rename_body_story_story_story_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stories"),
        ),
    ]
