# Generated by Django 4.1.3 on 2022-11-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_alter_story_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="anonymus",
            field=models.BooleanField(default=False),
        ),
    ]
