# Generated by Django 4.1.3 on 2023-01-04 11:12

import cloudinary_storage.storage
from django.db import migrations, models
import stories.validators


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0008_story_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage,
                upload_to="videos",
                validators=[stories.validators.validate_file_extension],
            ),
        ),
    ]
