# Generated by Django 4.1.3 on 2022-11-21 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("likes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stories.story"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
